apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicloud-operators-channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicloud-operators-channel
  template:
    metadata:
      labels:
        app: multicloud-operators-channel
    spec:
      serviceAccountName: multicloud-operators
      containers:
        - name: multicloud-operators-channel
          imagePullPolicy: IfNotPresent
          image: quay.io/open-cluster-management/multicloud-operators-channel:latest
          ports:
          - containerPort: 9443
            name: chn-whk-server
            protocol: TCP
          command:
          - /usr/local/bin/multicloud-operators-channel
          - --sync-interval=10
          - --zap-devel=true
          env:
           - name: WATCH_NAMESPACE
           - name: POD_NAME
             valueFrom:
               fieldRef:
                 fieldPath: metadata.name
           - name: POD_NAMESPACE
             valueFrom:
               fieldRef:
                 fieldPath: metadata.namespace
           - name: DEPLOYMENT_LABEL
             value: multicloud-operators-channel
           - name: OPERATOR_NAME
             value: multicloud-operators-channel
          resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                cpu: 500m
                memory: 512Mi
